
    platform :ios  
    pod 'Reachability',  '~> 3.0.0'  
    pod 'SBJson', '~> 4.0.0'  
      
    platform :ios, '7.0'  
    pod 'AFNetworking', '~> 2.0'

    pod 'Masonry', '~> 0.6.1'
    pod 'Classy', '~> 0.2.4'
    pod 'ClassyLiveLayout', '~> 0.6.0'